import type { Model, Toolpath } from "./types";
import { simplifyClosedLoop, traceBoundaryLoops } from "./geometry";
import { clamp, fmt, sanitizeBaseName } from "./utils";

export function generateGcode(paths: Toolpath[], model: Model, imageName: string): string {
  const s = model.settings;
  const safeAbsolute = s.surfaceZ + s.safeZ;
  const lines = [
    `(ABS bicolor engraving: ${imageName.replace(/[()]/g, "")})`,
    `(Artwork ${fmt(model.finishedWidth)} x ${fmt(model.finishedHeight)} mm; depth cap ${fmt(s.targetDepth)} mm)`,
    `(V-bit ${fmt(s.vAngle, 1)} deg; width at cap ${fmt(s.cutWidth)} mm; verify on scrap)`,
    "G21",
    "G90",
    "G17",
    "G94",
    `G0 Z${fmt(safeAbsolute)}`
  ];
  if (s.emitSpindle) lines.push(`M3 S${s.spindleRpm}`);

  for (const path of paths) {
    if (!path.points.length) continue;
    const first = path.points[0];
    lines.push(`G0 X${fmt(first.x)} Y${fmt(first.y)}`);
    if (path.kind === "detail") {
      const firstDepth = clamp(first.depth || 0, 0, s.targetDepth);
      lines.push(`G1 Z${fmt(s.surfaceZ - firstDepth)} F${fmt(s.feedPlunge, 1)}`);
      if (path.points.length === 1) {
        lines.push(`G0 Z${fmt(safeAbsolute)}`);
        continue;
      }
      for (let i = 1; i < path.points.length; i++) {
        const p = path.points[i];
        const depth = clamp(p.depth || 0, 0, s.targetDepth);
        lines.push(`G1 X${fmt(p.x)} Y${fmt(p.y)} Z${fmt(s.surfaceZ - depth)}${i === 1 ? ` F${fmt(s.feedXY, 1)}` : ""}`);
      }
    } else {
      lines.push(`G1 Z${fmt(s.surfaceZ - (path.depth ?? 0))} F${fmt(s.feedPlunge, 1)}`);
      for (let i = 1; i < path.points.length; i++) {
        const p = path.points[i];
        lines.push(`G1 X${fmt(p.x)} Y${fmt(p.y)}${i === 1 ? ` F${fmt(s.feedXY, 1)}` : ""}`);
      }
    }
    lines.push(`G0 Z${fmt(safeAbsolute)}`);
  }
  if (s.emitSpindle) lines.push("M5");
  lines.push(`G0 Z${fmt(safeAbsolute)}`, "M2", "");
  return lines.join("\n");
}

export function generateSvg(mask: Uint8Array, model: Model, imageName: string): string {
  const rawLoops = traceBoundaryLoops(mask, model.width, model.height);
  const tolerancePx = model.settings.simplifyTolerance / model.mmPerPx;
  const pathCommands: string[] = [];
  for (const loop of rawLoops) {
    const points = simplifyClosedLoop(loop, tolerancePx);
    if (points.length < 4) continue;
    const first = points[0];
    pathCommands.push(`M ${fmt(first.x * model.scaleX)} ${fmt(first.y * model.scaleY)}`);
    for (let i = 1; i < points.length - 1; i++) {
      pathCommands.push(`L ${fmt(points[i].x * model.scaleX)} ${fmt(points[i].y * model.scaleY)}`);
    }
    pathCommands.push("Z");
  }
  return `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<svg xmlns="http://www.w3.org/2000/svg" width="${fmt(model.finishedWidth)}mm" height="${fmt(model.finishedHeight)}mm" viewBox="0 0 ${fmt(model.finishedWidth)} ${fmt(model.finishedHeight)}">\n` +
    `  <title>${sanitizeBaseName(imageName)} engraving mask</title>\n` +
    `  <desc>Black regions are intended for engraving. Generated by ABS Bicolor V-Engraver.</desc>\n` +
    `  <path d="${pathCommands.join(" ")}" fill="#000000" fill-rule="evenodd"/>\n` +
    `</svg>\n`;
}
