import type { Model } from "./types";
import { simplifyClosedLoop, traceBoundaryLoops } from "./geometry";
import { fmt, sanitizeBaseName } from "./utils";

export function generateSvg(mask: Uint8Array, model: Model, imageName: string): string {
  const rawLoops = traceBoundaryLoops(mask, model.width, model.height);
  const tolerancePx = model.settings.simplifyTolerance / model.mmPerPx;
  const pathCommands: string[] = [];
  for (const loop of rawLoops) {
    const points = simplifyClosedLoop(loop, tolerancePx);
    if (points.length < 4) continue;
    const first = points[0];
    pathCommands.push(`M ${fmt(first.x * model.scaleX)} ${fmt(first.y * model.scaleY)}`);
    for (let i = 1; i < points.length - 1; i++) {
      pathCommands.push(`L ${fmt(points[i].x * model.scaleX)} ${fmt(points[i].y * model.scaleY)}`);
    }
    pathCommands.push("Z");
  }
  return `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<svg xmlns="http://www.w3.org/2000/svg" width="${fmt(model.finishedWidth)}mm" height="${fmt(model.finishedHeight)}mm" viewBox="0 0 ${fmt(model.finishedWidth)} ${fmt(model.finishedHeight)}">\n` +
    `  <title>${sanitizeBaseName(imageName)} engraving mask</title>\n` +
    `  <desc>Black regions are intended for engraving. Generated by ABS Bicolor V-Engraver.</desc>\n` +
    `  <path d="${pathCommands.join(" ")}" fill="#000000" fill-rule="evenodd"/>\n` +
    `</svg>\n`;
}
